version: '3.4'
services:
  erp-produto:
    image: dehemart/erp-gateway:latest
    container_name: erp-gateway
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      SPRING_PROFILES_ACTIVE: local
      SPRING_CLOUD_CONFIG_URI: http://172.17.0.1:8888
